/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufsc.maven.extrairEsquemas.views;

import com.ufsc.maven.extrairEsquemas.util.RedisConnector;
import com.ufsc.maven.extrairEsquemas.util.MongoConnector;
import com.ufsc.maven.extrairEsquemas.presenter.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import redis.clients.jedis.exceptions.JedisDataException;

/**
 *
 * @author lisa
 */
public class MainApp extends javax.swing.JFrame {
    
    private MongoConnector mongo;
    private RedisConnector redis;
    
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInputPanel = new javax.swing.JPanel();
        labelRedis = new javax.swing.JLabel();
        labelAdress = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        inputAdressField = new javax.swing.JFormattedTextField();
        inputPortField = new javax.swing.JFormattedTextField();
        inputVerify = new javax.swing.JButton();
        inputPassField = new javax.swing.JPasswordField();
        jOutputPanel = new javax.swing.JPanel();
        mongoLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        authLabel = new javax.swing.JLabel();
        databaseLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        databaseField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        outputAdressField = new javax.swing.JFormattedTextField();
        outputPortField = new javax.swing.JFormattedTextField();
        outputVerify = new javax.swing.JButton();
        extractSchema = new javax.swing.JButton();
        collectionLabel = new javax.swing.JLabel();
        collectionField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input");

        labelRedis.setText("Redis");

        labelAdress.setText("Adress:");

        labelPort.setText("Port: ");

        labelPass.setText("Pass Auth: ");

        inputAdressField.setName(""); // NOI18N

        inputVerify.setText("Verify");
        inputVerify.setToolTipText("");
        inputVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputVerifyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInputPanelLayout = new javax.swing.GroupLayout(jInputPanel);
        jInputPanel.setLayout(jInputPanelLayout);
        jInputPanelLayout.setHorizontalGroup(
            jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInputPanelLayout.createSequentialGroup()
                .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInputPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(labelRedis))
                    .addGroup(jInputPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInputPanelLayout.createSequentialGroup()
                                .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAdress)
                                    .addComponent(labelPort))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputPortField)
                                    .addComponent(inputAdressField)))
                            .addGroup(jInputPanelLayout.createSequentialGroup()
                                .addComponent(labelPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInputPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(inputVerify)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jInputPanelLayout.setVerticalGroup(
            jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRedis)
                .addGap(13, 13, 13)
                .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPort)
                        .addComponent(inputPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInputPanelLayout.createSequentialGroup()
                        .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdress)
                            .addComponent(inputAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)))
                .addGap(31, 31, 31)
                .addGroup(jInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPass)
                    .addComponent(inputPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(inputVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputAdressField.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Input", jInputPanel);
        jInputPanel.getAccessibleContext().setAccessibleName("Input");

        mongoLabel.setText("MongoDB");

        adressLabel.setText("Address: ");

        portLabel.setText("Port: ");

        authLabel.setText("Auth:");

        databaseLabel.setText("Database: ");

        usernameLabel.setText("Username: ");

        passwordLabel.setText("Password: ");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        outputAdressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputAdressFieldActionPerformed(evt);
            }
        });

        outputPortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPortFieldActionPerformed(evt);
            }
        });

        outputVerify.setText("Verify");
        outputVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputVerifyActionPerformed(evt);
            }
        });

        extractSchema.setText("Extract Raw Schema");
        extractSchema.setEnabled(false);
        extractSchema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extractSchemaMouseClicked(evt);
            }
        });

        collectionLabel.setText("Collection");

        javax.swing.GroupLayout jOutputPanelLayout = new javax.swing.GroupLayout(jOutputPanel);
        jOutputPanel.setLayout(jOutputPanelLayout);
        jOutputPanelLayout.setHorizontalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(authLabel))
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(mongoLabel))
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jOutputPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jOutputPanelLayout.createSequentialGroup()
                                .addComponent(databaseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(databaseField))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOutputPanelLayout.createSequentialGroup()
                                .addComponent(outputVerify)
                                .addGap(155, 155, 155))
                            .addGroup(jOutputPanelLayout.createSequentialGroup()
                                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(portLabel)
                                    .addComponent(adressLabel))
                                .addGap(24, 24, 24)
                                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outputAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outputPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                        .addComponent(extractSchema)
                        .addGap(55, 55, 55))
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addGroup(jOutputPanelLayout.createSequentialGroup()
                                .addComponent(collectionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(collectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jOutputPanelLayout.setVerticalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mongoLabel)
                .addGap(14, 14, 14)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portLabel))
                .addGap(18, 18, 18)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressLabel))
                .addGap(14, 14, 14)
                .addComponent(authLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(databaseLabel)
                    .addComponent(databaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jOutputPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(collectionLabel))
                    .addComponent(collectionField, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputVerify)
                    .addComponent(extractSchema))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Output", jOutputPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Input");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void outputPortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPortFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputPortFieldActionPerformed

    private void outputAdressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputAdressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputAdressFieldActionPerformed

    private void inputVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputVerifyMouseClicked
        // TODO add your handling code here:
        redis = new RedisConnector();
        //redis.connect(inputAdressField.getText(), inputPortField.getText(), String.valueOf(inputPassField.getPassword()));
        if (redis.connect(inputAdressField.getText(), inputPortField.getText(), String.valueOf(inputPassField.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Informações verificadas com sucesso.");
            //inputVerify.setEnabled(false);
        }
    }//GEN-LAST:event_inputVerifyMouseClicked

    private void outputVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputVerifyActionPerformed
        mongo = new MongoConnector();

        if (mongo.connect(outputAdressField.getText(), outputPortField.getText(), usernameField.getText(),
                String.valueOf(passwordField.getPassword()), databaseField.getText())) {
            JOptionPane.showMessageDialog(null, "Informações verificadas com sucesso,"
                    + " habilitando processo de Raw Schema.");

            extractSchema.setEnabled(true);
            //outputVerify.setEnabled(false);

        }
    }//GEN-LAST:event_outputVerifyActionPerformed

    private void extractSchemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extractSchemaMouseClicked

        Iterator iterator = new Iterator(mongo, redis);

        try {
            iterator.readRedis();
        } catch (Exception ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_extractSchemaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new MainApp().setVisible(true);
            }
        });
    }
   
    private javax.swing.JPasswordField JPassword;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel authLabel;
    private javax.swing.JTextField collectionField;
    private javax.swing.JLabel collectionLabel;
    private javax.swing.JTextField databaseField;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JButton extractSchema;
    private javax.swing.JFormattedTextField inputAdressField;
    private javax.swing.JPasswordField inputPassField;
    private javax.swing.JFormattedTextField inputPortField;
    private javax.swing.JButton inputVerify;
    private javax.swing.JPanel jInputPanel;
    private javax.swing.JPanel jOutputPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAdress;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelRedis;
    private javax.swing.JLabel mongoLabel;
    private javax.swing.JFormattedTextField outputAdressField;
    private javax.swing.JFormattedTextField outputPortField;
    private javax.swing.JButton outputVerify;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
